// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission62.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230211224754_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.AddMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("addMovies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action",
                            Director = "Sam Raimi",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Spider-Man",
                            Year = 2002
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Sport/Drama",
                            Director = "M. Night Shyamalan",
                            Edited = false,
                            Rating = "PG",
                            Title = "Invincible",
                            Year = 2006
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Comedy/Christmas/Musical ",
                            Director = "Sean Anders",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "spirited ",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
